### ISSUE TITLE
Document the init command

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock-cli#2]
Reading through the source I discovered there is an init command. Cool @thomastuts :)

I use the `upgrade` command all the time. This will be handy for my Bedrock speedrun video. Not sure if the command will still work so I will check it out and then document it.

**Comment by Wolfr** [comment]
Is this documentation still correct?

https://github.com/mono-company/bedrock-cli/blob/master/README.md

**Comment by thomastuts** [comment]
Yep. I changed the URL of the Bootstrap starter repo since it looks like it changed, but the docs are still up-to-date.

**Comment by Wolfr** [comment]
OK I will test this and then write a blog post about bedrock cli changes on the Bedrock blog.

(The least read blog on the planet ;))
