### ISSUE TITLE
Updating CLI

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock-cli#3]
<img width="663" alt="screen shot 2017-03-07 at 16 29 33" src="https://cloud.githubusercontent.com/assets/12690/23663591/5089b46e-0353-11e7-8e60-5e8f3172a915.png">

If I update CLI it talks about 1.0.0, but package.json updated 3 months ago is 1.1.0, and the newest commit maybe does not have a version?

https://github.com/mono-company/bedrock-cli/blob/master/package.json

**Comment by Wolfr** [comment]
Do we need to publish this to npm or something like that?

**Comment by thomastuts** [comment]
Yes, a new version needs to be published manually to npm. I don't have access rights to the module, I think @xavez set that up.

**Comment by Wolfr** [comment]
Was the 1.1 version ever published?

**Comment by xavez** [comment]
@thomastuts added you to the npmjs package. @Wolfr if you give me your npmjs account, I can also add you.

**Comment by xavez** [comment]
Meanwhile, I’ve published 1.1.0 :-)

**Comment by Wolfr** [comment]
@xavez I am "wolfr" on npmjs

**Comment by Wolfr** [comment]
@xavez is the latest fix in 1.1.0 or does this become 1.1.1?

**Comment by Wolfr** [comment]
Imo it fixes a lot so it could be a 1.2 as well

**Comment by xavez** [comment]
@Wolfr npm just uses the versioning from the project, the last one being `1.1.0`

**Comment by Wolfr** [comment]
so the newest change is already in there. OK
